# Generated by Django 5.2.9 on 2026-01-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('new', 'Just Starting'), ('some', 'Some Experience'), ('experienced', 'Experienced')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_goal',
            field=models.CharField(blank=True, choices=[('reduce_stuttering', 'Reduce Stuttering'), ('build_confidence', 'Build Confidence'), ('professional', 'Professional Speaking'), ('therapy_support', 'Support Therapy')], max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('search', 'Search Engine'), ('social', 'Social Media'), ('friend', 'Friend or Family'), ('therapist', 'Speech Therapist'), ('other', 'Other')], max_length=50),
        ),
    ]
