# Generated by Django 5.2.9 on 2026-01-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_age_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechsession',
            name='analysis_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='speechsession',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='recordings/'),
        ),
        migrations.AddField(
            model_name='speechsession',
            name='blocks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='speechsession',
            name='flagged_words',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='speechsession',
            name='interjections_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='speechsession',
            name='prolongations_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='speechsession',
            name='repetitions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='speechsession',
            name='stuttering_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='speechsession',
            name='transcription_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='speechsession',
            name='transcription_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='speechsession',
            name='session_type',
            field=models.CharField(choices=[('speech_analysis', 'Speech Analysis'), ('tongue_twister', 'Tongue Twister'), ('reading_exercise', 'Reading Exercise'), ('conversation', 'Conversation Practice')], default='speech_analysis', max_length=50),
        ),
    ]
