# Generated by Django 4.2.27 on 2026-03-11 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_speechsession_analysis_data_speechsession_audio_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(help_text="The tongue twister or exercise text"),
                ),
                (
                    "stutter_type",
                    models.CharField(
                        choices=[
                            ("repetition", "Repetition"),
                            ("prolongation", "Prolongation"),
                            ("blocking", "Blocking"),
                            ("interjection", "Interjection"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "xp_reward",
                    models.IntegerField(
                        default=10, help_text="XP points awarded for completing"
                    ),
                ),
                (
                    "tips",
                    models.TextField(
                        blank=True, help_text="Tips for practicing this exercise"
                    ),
                ),
                (
                    "focus_sounds",
                    models.CharField(
                        blank=True,
                        help_text="Sounds to focus on, e.g., 'b, p, t'",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order within difficulty level"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["stutter_type", "difficulty", "order"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("score", models.IntegerField(default=0, help_text="Score out of 100")),
                ("duration_seconds", models.IntegerField(default=0)),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to="exercise_recordings/"
                    ),
                ),
                ("transcription", models.TextField(blank=True)),
                ("feedback", models.JSONField(blank=True, default=dict)),
                ("xp_earned", models.IntegerField(default=0)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="main.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
            },
        ),
    ]
