# Generated by Django 4.2.27 on 2026-03-11 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_exercise_exerciseattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("repetition", "Repetition"),
                            ("prolongation", "Prolongation"),
                            ("blocking", "Blocking"),
                            ("interjection", "Interjection"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expected_text", models.TextField()),
                ("transcribed_text", models.TextField(blank=True)),
                ("accuracy_score", models.FloatField(default=0)),
                ("fluency_score", models.FloatField(default=0)),
                ("overall_score", models.FloatField(default=0)),
                ("xp_earned", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("duration_seconds", models.IntegerField(default=0)),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to="exercise_recordings/"
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("word_matches", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="exerciseattempt",
            name="exercise",
        ),
        migrations.RemoveField(
            model_name="exerciseattempt",
            name="user",
        ),
        migrations.DeleteModel(
            name="Exercise",
        ),
        migrations.DeleteModel(
            name="ExerciseAttempt",
        ),
    ]
